spring:
    application:
        name: product
    datasource:
      dirver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost/springcloud_sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
